---
title: "Bilgi Yönetim Sistemleri - Bitirme Projesi Rapor : 
Semih Sarı 200401071,
Merve Yılmaz 210401009,
Berat Öcal 200401017,
Ümit Atakan Günel 210401004"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Q1: İş probleminin tanımı 

Türkiye’nin en büyük online hizmet platformu olan Armut, hizmet verenler ile hizmet almak isteyenleri buluşturmaktadır. Kullanıcılar, bilgisayar veya akıllı telefonları üzerinden birkaç dokunuşla temizlik, tadilat, nakliyat gibi çeşitli hizmetlere kolayca ulaşabilmektedir. Bu raporda, Armut platformunda hizmet alan kullanıcıların almış oldukları servis ve kategorileri içeren veri seti kullanılarak, Association Rule Learning yöntemi ile bir ürün tavsiye sistemi oluşturulması hedeflenmektedir.Bu sistem, kullanıcıların ilgilerine göre hizmet önerileri sunarak müşteri memnuniyetini ve hizmet kalitesini artırmayı amaçlamaktadır.

SuiteCRM'in müşteri yönetimi, satış yönetimi, pazarlama otomasyonu ve raporlama özelliklerinden yararlanılarak bu hedefe ulaşılacaktır. SuiteCRM'in açık kaynaklı ve özelleştirilebilir yapısı, düşük maliyetli ve esnek çözümler sunarak iş süreçlerinin optimize edilmesine katkı sağlayacaktır. Bu nedenle SuiteCRM, bu proje için ideal bir BYS platformu olarak seçilmiştir.


## Q2: İş problemini çözmede kullanılacak data seti 

# Veri Seti
*******************************
*Veri seti müşterilerin aldıkları servislerden ve bu servislerin kategorilerinden oluşmaktadır.*
*Alınan her hizmetin tarih ve saat bilgisini içermektedir.*
 
- **UserId**: Müşteri numarası
- **ServiceId**: Her kategoriye ait anonimleştirilmiş servislerdir. (Örnek : *Temizlik* kategorisi altında *koltuk yıkama* servisi)
  - *Bir ServiceId farklı kategoriler altında bulanabilir ve farklı kategoriler altında farklı servisleri ifade eder.*
  - (Örnek: CategoryId’si *7* ServiceId’si *4* olan hizmet *petek temizliği* iken CategoryId’si *2* ServiceId’si *4* olan hizmet *mobilya montaj*)
- **CategoryId**: Anonimleştirilmiş kategorilerdir. (Örnek : *Temizlik, nakliyat, tadilat* kategorisi)
- **CreateDate**: Hizmetin satın alındığı tarih
- **Ad**: Müşteri adı
- **Soyad**: Müşteri soyadı
- **email**: Müşteri e-posta adresi
 
```{r echo=FALSE}

library(readr)

data <- read_csv("data_raw.csv",show_col_types = FALSE)
print(head(data))

```
 
 

 
 
 
 
 
 
### Veri Seti Kaynağı
Bu veri seti, Kaggle platformundan bulunmuştur. [Armut Data](https://www.kaggle.com/datasets/sumeyraaksekiboz/armut-data/data) adlı veri setidir.
 
- **Veriyi Toplayan/Yaratanlar**: Veri setini oluşturanlar, Armut platformu tarafından müşterilerin hizmet satın alma işlemleri sırasında otomatik olarak toplanmış verileri derlemiştir.
- **Veri Toplama Yöntemi**: Armut platformu, kullanıcıların platform üzerindeki hizmet taleplerini ve satın alımlarını kaydederek bu veriyi oluşturmuştur.
 
### Veri Üzerinde Yapılan Değişiklikler
Veri seti üzerinde herhangi bir değişiklik yapılmamıştır. Ancak sentetik veri eklemek için ad, soyad ve e-posta bilgileri gibi ek alanlar oluşturulmuştur.
 
### Sentetik Veri Üretimi
Sentetik veri eklemek için ad, soyad ve e-posta bilgileri gibi ek alanlar oluşturulmuştur. Bu bilgiler, gerçek kullanıcı verilerinden türetilmemiş ve rastgele oluşturulmuştur. Sentetik veri eklemek için kullanılan süreç, sentetik veri üretimi için yaygın olarak kullanılan Python kütüphaneleri kullanılarak gerçekleştirilmiştir.
 
**Sonuç**
Bu veri seti, müşterilerin hizmet satın alma alışkanlıklarını analiz etmek ve hizmet kategorileri arasındaki ilişkileri incelemek için kullanılacaktır. Kaggle platformundan elde edilen bu veri seti, gerçek dünya kullanıcı davranışlarını temsil etmektedir ve çeşitli analizler için potansiyel sunmaktadır. Sentetik veri eklenerek, veri setinin zenginleştirilmesi ve daha geniş kapsamlı analizler yapılabilmesi sağlanmıştır.








